# Generated by Django 3.0.4 on 2020-03-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_make', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('miles', models.CharField(max_length=100)),
                ('repair', models.CharField(max_length=500)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='garage.Year')),
            ],
        ),
    ]
