# Generated by Django 3.0.4 on 2020-03-11 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='make',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repair',
            name='year',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
