# Generated by Django 3.0.4 on 2020-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20200311_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repair',
            field=models.TextField(max_length=255),
        ),
    ]
